version: '3.8'
services:
  ollama:
    image: ollama/ollama:latest
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    environment:
      OLLAMA_HOST: 0.0.0.0

  chroma:
    image: chromadb/chroma:latest
    restart: always
    ports:
      - "8001:8000"
    volumes:
      - chroma-data:/chroma

  backend:
    build: ./
    restart: always
    env_file:
      - .env
    depends_on:
      - ollama
      - chroma
    ports:
      - "8000:8000"
    volumes:
      - ./repositories:/repositories

volumes:
  ollama-data:
  chroma-data:
