version: '3.8'
services:
  backend:
    build: ./
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./repositories:/repositories
      - ./logs:/app/logs  # Optional: for persistent logs
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    # Health check (optional)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

# Note: Removed ollama and chroma volumes since we're using external services
# (DeepInfra API and Pinecone) that don't require local containers